### ISSUE TITLE
3 teams shown when team are set to 2

### ISSUE THREAD

**Issue by 1-alex98** [beyond-all-reason/bar-lobby#212]
![image](https://github.com/beyond-all-reason/bar-lobby/assets/19996713/b482314e-2a95-48be-ae85-f833ee748fd5)

**Comment by Jazcash** [comment]
It always creates an empty team, this is partly by design - if the players wish to create a new team, they can join the empty team to do so, chobby also does this. For SPADS battles however, there is a set number of teams, so maybe we shouldn't show a spare team in this case if the current number of active teams is less than the max. Tbh though that sounds a bit messy and there's currently a bug in SPADS with how that info gets sent to the lobby (it doesn't always send SPADS-specific battle info message on join) so I'd rather leave that logic alone for now
