### ISSUE TITLE
Changing tabs causes styling issues

### ISSUE THREAD

**Issue by JRugen** [beyond-all-reason/bar-lobby#248]
When changing tabs, the content of the new tab loads underneath the content of the old tab. This quickly adjusts, but shouldn't be shown to the user when changing tabs.

**Comment by Jazcash** [comment]
I think this was intentional but intended to be temporary: https://github.com/beyond-all-reason/bar-lobby/commit/8a9b592700f393b61d986c55cd99d1b044642ca2

The transition mode `out-in` is desired but was causing a much more critical bug with the whole Vue renderer crashing: https://github.com/beyond-all-reason/bar-lobby/issues/61

I believe there's still open PRs to vue-core that I and several others have submitted to fix this and some similar issues but they still haven't been merged. Best solution for us to fix the issue right now (if it's bothering us too much) is to fix the issue in our local vue package using [patch-package](https://www.npmjs.com/package/patch-package), which we're already doing for one of the vue bugs (see patches folder in root).
